### ISSUE TITLE
GPU usage failed

### ISSUE THREAD

**Issue by hyb965149985** [MATony/ImageStitch#2]
Hello, I am getting an error when calling the pyd file, suggesting that the DLL file is missing, I would like to ask you how to solve it, thank you.
MISSING：
OPENCV_CORE331.DLL
OPENCV_CUDAFEATURES2D331.DLL
OPENCV_XFEATURES2D331.DLL
API-MAPI-MS-WIN-CORE-WINRT-L1-1-0.DLL
S-WIN-APPMODEL-RUNTIME-L1-1-0.DLL

**Comment by MATony** [comment]
Thank you for your testing.
The sift and surf in Opencv is prohibitted because of its patents. So i used Cmake to rebuild opencv 3.3.1 contrib with cuda 9.0 and programmed it with python and c++ by using boost library a year ago.
Unfortunately, i made a terrible mistake that i just saved the code and forgot the setting in VS2015. 
Now, I can run the gpu code in my windows computer and can not run this code to other computers, because the dll does not include in my code.
I am so sorry about it, i am trying to fix this problem recently.
Please use the sift and surf in cpu mode now.  And if i upate the code, i will inform to you. Please feel free to tell me your usage problem at any time.
By the way, what the software do you use to find this problem. Is this enough?
Thank you for your pointing.

**Comment by MATony** [comment]
> Hello, I am getting an error when calling the pyd file, suggesting that the DLL file is missing, I would like to ask you how to solve it, thank you.
> MISSING：
> OPENCV_CORE331.DLL
> OPENCV_CUDAFEATURES2D331.DLL
> OPENCV_XFEATURES2D331.DLL
> API-MAPI-MS-WIN-CORE-WINRT-L1-1-0.DLL
> S-WIN-APPMODEL-RUNTIME-L1-1-0.DLL

Thank you for your testing. I made a bad mistake that i just saved the code a year ago and forgot the programming setting in VS2015. I am trying to solve this problem recently. I will inform you if i have solved. By the way, what software do you use to find these dll. Is this enough? I am hoping you help me to solve this problem. Before that, please use cpu mode.

**Comment by hyb965149985** [comment]
Thank you for your reply. I used the depends22_x64 tool to get the missing DLL file, but it didn't solve it because I could not find the OPENCV_CORE331.DLL file on the Internet. I am using the CPU version of the program everything works fine, thank you for the code, I am planning to use it in my project. Because I want to reduce the running time, I hope to use the GPU version, thank you for sharing.




------------------ 原始邮件 ------------------
发件人: "马博渊"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 中午12:04
收件人: "MATony/ImageStitch"<ImageStitch@noreply.github.com>;
抄送: "郑州大学_霍一博"<965149985@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MATony/ImageStitch] GPU usage failed (#2)



Thank you for your testing.
 The sift and surf in Opencv is prohibitted because of its patents. So i used Cmake to rebuild opencv 3.3.1 contrib with cuda 9.0 and programmed it with python and c++ by using boost library a year ago.
 Unfortunately, i made a terrible mistake that i just saved the code and forgot the setting in VS2015.
 Now, I can run the gpu code in my windows computer and can not run this code to other computers, because the dll does not include in my code.
 I am so sorry about it, i am trying to fix this problem recently.
 Please use the sift and surf in cpu mode now.And if i upate the code, i will inform to you. Please feel free to tell me your usage problem at any time.
 By the way, what the software do you use to find this problem. Is this enough?
 Thank you for your pointing.

**Comment by hyb965149985** [comment]
Thank you for your suggestion, I will try it hard, I will tell you the progress.




------------------ 原始邮件 ------------------
发件人: "马博渊"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 中午12:10
收件人: "MATony/ImageStitch"<ImageStitch@noreply.github.com>;
抄送: "郑州大学_霍一博"<965149985@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MATony/ImageStitch] GPU usage failed (#2)



 Hello, I am getting an error when calling the pyd file, suggesting that the DLL file is missing, I would like to ask you how to solve it, thank you.
 MISSING：
 OPENCV_CORE331.DLL
 OPENCV_CUDAFEATURES2D331.DLL
 OPENCV_XFEATURES2D331.DLL
 API-MAPI-MS-WIN-CORE-WINRT-L1-1-0.DLL
 S-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
  Thank you for your testing. I made a bad mistake that i just saved the code a year ago and forgot the programming setting in VS2015. I am trying to solve this problem recently. I will inform you if i have solved. By the way, what software do you use to find these dll. Is this enough? I am hoping you help me to solve this problem. Before that, please use cpu mode.

**Comment by MATony** [comment]
> Thank you for your reply. I used the depends22_x64 tool to get the missing DLL file, but it didn't solve it because I could not find the OPENCV_CORE331.DLL file on the Internet. I am using the CPU version of the program everything works fine, thank you for the code, I am planning to use it in my project. Because I want to reduce the running time, I hope to use the GPU version, thank you for sharing.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "马博渊"<notifications@github.com>; 发送时间: 2019年4月27日(星期六) 中午12:04 收件人: "MATony/ImageStitch"<ImageStitch@noreply.github.com>; 抄送: "郑州大学_霍一博"<965149985@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [MATony/ImageStitch] GPU usage failed (#2) Thank you for your testing. The sift and surf in Opencv is prohibitted because of its patents. So i used Cmake to rebuild opencv 3.3.1 contrib with cuda 9.0 and programmed it with python and c++ by using boost library a year ago. Unfortunately, i made a terrible mistake that i just saved the code and forgot the setting in VS2015. Now, I can run the gpu code in my windows computer and can not run this code to other computers, because the dll does not include in my code. I am so sorry about it, i am trying to fix this problem recently. Please use the sift and surf in cpu mode now.And if i upate the code, i will inform to you. Please feel free to tell me your usage problem at any time. By the way, what the software do you use to find this problem. Is this enough? Thank you for your pointing. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I have updated the code and the readme about GPU version. Please check it and feel free to tell me at any time. Please be so kind to star my repository and cite our work in your paper.
另外，都是中国人，可以用中文沟通节省时间

**Comment by hyb965149985** [comment]
恩呢，谢谢您，我昨天按照你的提示运行Gpu版本的成功了，使用surf的没问题，但是使用 orf特征的时候报错：
OpenCV Error: Unsupported format or combination of formats (unsupported combination of query.depth() and norm) in `anonymous-namespace'::BFMatcher_Impl::matchAsync, file D:\opencv3.3.1\opencv\sources\modules\cudafeatures2d\src\brute_force_matcher.cpp, line 363
RuntimeError: D:\opencv3.3.1\opencv\sources\modules\cudafeatures2d\src\brute_force_matcher.cpp:363: error: (-210) unsupported combination of query.depth() and norm in function `anonymous-namespace'::BFMatcher_Impl::matchAsync
在matches = self.npToListForMatches(myGpuFeatures.matchDescriptors(np.array(featuresA), np.array(featuresB), 3, self.orbMaxDistance))这一句话中出现问题。，我把它改为 surf的特征匹配方式就可以运行。
我是打算使用显微镜做细胞结构的拼接图。参加一个省级的挑战杯竞赛。目前我还没有拿到我的数据集。硬件平台正在搭建中。
十分感谢您对我的帮助。如果我未来发表论文的时候一定引用你们的工作，再次感谢。
------------------ 原始邮件 ------------------
发件人: "马博渊"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 中午12:39
收件人: "MATony/ImageStitch"<ImageStitch@noreply.github.com>;
抄送: "郑州大学_霍一博"<965149985@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MATony/ImageStitch] GPU usage failed (#2)



 Thank you for your reply. I used the depends22_x64 tool to get the missing DLL file, but it didn't solve it because I could not find the OPENCV_CORE331.DLL file on the Internet. I am using the CPU version of the program everything works fine, thank you for the code, I am planning to use it in my project. Because I want to reduce the running time, I hope to use the GPU version, thank you for sharing.
 …
 ------------------ 原始邮件 ------------------ 发件人: "马博渊"notifications@github.com; 发送时间: 2019年4月27日(星期六) 中午12:04 收件人: "MATony/ImageStitch"ImageStitch@noreply.github.com; 抄送: "郑州大学_霍一博"965149985@qq.com; "Author"author@noreply.github.com; 主题: Re: [MATony/ImageStitch] GPU usage failed (#2) Thank you for your testing. The sift and surf in Opencv is prohibitted because of its patents. So i used Cmake to rebuild opencv 3.3.1 contrib with cuda 9.0 and programmed it with python and c++ by using boost library a year ago. Unfortunately, i made a terrible mistake that i just saved the code and forgot the setting in VS2015. Now, I can run the gpu code in my windows computer and can not run this code to other computers, because the dll does not include in my code. I am so sorry about it, i am trying to fix this problem recently. Please use the sift and surf in cpu mode now.And if i upate the code, i will inform to you. Please feel free to tell me your usage problem at any time. By the way, what the software do you use to find this problem. Is this enough? Thank you for your pointing. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  I have updated the code and the readme about GPU version. Please check it and feel free to tell me at any time. Please be so kind to star my repository and cite our work in your paper.
 另外，都是中国人，可以用中文沟通节省时间

**Comment by hyb965149985** [comment]
我使用你GitHub上的DLL文件出错，提示缺少DLL文件，但是我使用自己cmake的opencv3.3.1就可以使用，仅仅orb的GPU匹配出错，不过这不影响我使用，谢谢你。另外，我把我加载的DLL文件发给你，希望有一点帮助。


------------------ 原始邮件 ------------------
发件人: "马博渊"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 中午12:39
收件人: "MATony/ImageStitch"<ImageStitch@noreply.github.com>;
抄送: "郑州大学_霍一博"<965149985@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MATony/ImageStitch] GPU usage failed (#2)



 Thank you for your reply. I used the depends22_x64 tool to get the missing DLL file, but it didn't solve it because I could not find the OPENCV_CORE331.DLL file on the Internet. I am using the CPU version of the program everything works fine, thank you for the code, I am planning to use it in my project. Because I want to reduce the running time, I hope to use the GPU version, thank you for sharing.
 …
 ------------------ 原始邮件 ------------------ 发件人: "马博渊"notifications@github.com; 发送时间: 2019年4月27日(星期六) 中午12:04 收件人: "MATony/ImageStitch"ImageStitch@noreply.github.com; 抄送: "郑州大学_霍一博"965149985@qq.com; "Author"author@noreply.github.com; 主题: Re: [MATony/ImageStitch] GPU usage failed (#2) Thank you for your testing. The sift and surf in Opencv is prohibitted because of its patents. So i used Cmake to rebuild opencv 3.3.1 contrib with cuda 9.0 and programmed it with python and c++ by using boost library a year ago. Unfortunately, i made a terrible mistake that i just saved the code and forgot the setting in VS2015. Now, I can run the gpu code in my windows computer and can not run this code to other computers, because the dll does not include in my code. I am so sorry about it, i am trying to fix this problem recently. Please use the sift and surf in cpu mode now.And if i upate the code, i will inform to you. Please feel free to tell me your usage problem at any time. By the way, what the software do you use to find this problem. Is this enough? Thank you for your pointing. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  I have updated the code and the readme about GPU version. Please check it and feel free to tell me at any time. Please be so kind to star my repository and cite our work in your paper.
 另外，都是中国人，可以用中文沟通节省时间
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

MYGpuFeatures.rar (76.88M, 2019年05月28日 14:21 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2537356652cb05cc4232b25f113006180703065e5409520f4e530350511d0053560618045653041a5655075e06015154500000073721347a3a704513715555431645501519425545630a&code=c75f7047

**Comment by MATony** [comment]
我更新代码，需要把pyd和dll放在一个文件夹里，我在ImageUtility里面更新了一句
from myGpuFeatures import myGpuFeatures
另外，orb那个我在研究下。
给我的整体感觉，orb效果比较差，我一般只用sift或者surf

**Comment by MATony** [comment]
另外，如果你能反编译成果，尝试把myGpuFeatures.cpp的
matcher = cv::cuda::DescriptorMatcher::createBFMatcher(cv::NORM_HAMMING);
换成：
matcher = cv::cuda::DescriptorMatcher::createBFMatcher(cv::NORM_L2);

**Comment by hyb965149985** [comment]
谢谢你，我在使用 我的数据集的时候出现使用orb特征出现报错，在ImageUtility的234行 加入非空的判断就可以了。另外，我使用渐入渐出的算法效果比使用最大值拼接的算法要差 。原因是渐入渐出在其他方向上的表现不好。
渐入渐出：

最大值：





------------------ 原始邮件 ------------------
发件人: "马博渊"<notifications@github.com>; 
发送时间: 2019年4月28日(星期天) 下午2:53
收件人: "MATony/ImageStitch"<ImageStitch@noreply.github.com>; 
抄送: "郑州大学_霍一博"<965149985@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MATony/ImageStitch] GPU usage failed (#2)



我更新代码，需要把pyd和dll放在一个文件夹里，我在ImageUtility里面更新了一句
 from myGpuFeatures import myGpuFeatures
 另外，orb那个我在研究下。
 给我的整体感觉，orb效果比较差，我一般只用sift或者surf

**Comment by MATony** [comment]
npToListForMatches 你的意思是发送给GPU的特征输入是空的吗？可是我在Stitcher.py的330行已经增加了判断了？？
if featuresA is not None and featuresB is not None:
你能把你234行代码提交个更新或者尝试发我看下吗？

由于我在拼接图像时会首先创造一个全0图像，所以FadeInFadeOut和trigonometric在边缘处表现效果较差，这相当于一个优化图像坐标的操作，所以可能我现在还没调好，如果可以的话，你发下你的图像我测试下

**Comment by hyb965149985** [comment]
不好意思，没有及时回复你的消息，在npToListForMatches这个函数里面报 AttributeError: 'NoneType' object has no attribute 'shape' 这个错误。我在234行添加一个判断就没出错了。我使用的是 orb特征。
我可以加下你的qq或微信吗？我发送附件的时候 显示对方所在服务商内存已达上限无法发送。




------------------ 原始邮件 ------------------
发件人: "马博渊"<notifications@github.com>; 
发送时间: 2019年4月28日(星期天) 晚上6:17
收件人: "MATony/ImageStitch"<ImageStitch@noreply.github.com>; 
抄送: "郑州大学_霍一博"<965149985@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MATony/ImageStitch] GPU usage failed (#2)



npToListForMatches 你的意思是发送给GPU的特征输入是空的吗？可是我在Stitcher.py的330行已经增加了判断了？？
 if featuresA is not None and featuresB is not None:
 你能把你234行代码提交个更新或者尝试发我看下吗？
 由于我在拼接图像时会首先创造一个全0图像，所以FadeInFadeOut和trigonometric在边缘处表现效果较差，这相当于一个优化图像坐标的操作，所以可能我现在还没调好，如果可以的话，你发下你的图像我测试下

**Comment by MATony** [comment]
我的微信号是MATony9296
