### ISSUE TITLE
could you give a tutorials  and make us easy how to run?

### ISSUE THREAD

**Issue by Tommy7013** [MATony/ImageStitch#3]
could you give a tutorials  and make us easy how to run?

**Comment by MATony** [comment]
You can just run main.py. If you want to use gpu version in your windows computer, you should download myGpuFeatures as shown in Readme. If you want to use CPU version, please set Stitcher.isGPUAvailable = False in Main.py

**Comment by MATony** [comment]
I will make the algorithm search the gpu automatly in the future work

**Comment by Tommy7013** [comment]
Hi, 
    Thank you for your reply. And it still have some problems when I try to run it.  Is there any dll files missing?Could I get your email? I want learn something from you.
Thanks

 The error is :  from myGpuFeatures import myGpuFeatures
ImportError: DLL load failed: 找不到指定的模块。


--




4203 Training building #4
Shanghai University of Engineering Science

333 Longteng Road, Songjiang District,

Shanghai, 201620,China
Tel:+8618516731643
email:tommy_crazy@163.com

At 2019-05-30 18:44:00, "马博渊" <notifications@github.com> wrote:


You can just run main.py. If you want to use gpu version in your windows computer, you should download myGpuFeatures as shown in Readme. If you want to use CPU version, please set Stitcher.isGPUAvailable = False in Main.py

**Comment by MATony** [comment]
My email is 793960628@qq.com and my wechat is MATony9296. You can contact with my or you can see the issue about the similar question and the note of gou version in readme.md: https://github.com/MATony/ImageStitch/issues/2
