### ISSUE TITLE
using a lot of memory

### ISSUE THREAD

**Issue by NextGuido** [MATony/ImageStitch#5]
你好，非常感谢你的项目，他对我非常有用。但是我在使用中发现了一些问题（我在linux下使用），希望请指教！
1、[如果在拼接图像过程前，使用numpy生成初始化图像的话](https://github.com/MATony/ImageStitch/blob/46eae39359f0366b65c6aaa2a3f914fd26551394/Stitcher.py#L416)，那么在拼接时，内存占用量会非常高（我有20x20张图片，每张图片尺寸为2448x2048，在拼接过程中内存占用量达到60G左右），如果图片过多有时候会出现MemoryError，请问有什么好的解决方法吗？
2、请问有没有可能对拼接的步骤进行优化加速？

再次谢谢您的帮助

**Comment by MATony** [comment]
你好
1. 关于内存问题，我采取的策略是首先计算出所有图像的偏移量，然后创造一个计算好的存储空间，再根据位移把每张图像放到相应位置上（函数getStitchByOffset），然后再保存整张图像。我以前也试过其他方法，比如把中间结果存起来，io的访问会降低速度，但对内存总耗量没有影响，这里存在一个问题，就是不论怎么拼，如果你要最终保存为一张图像，你肯定得先在内存中生成一个总图然后再存，这个总图会占用最大内存。你的图像如果按照uint8（我用的一般为灰度）存储，最后大小可能为20*20*2048*2048/1024/1024/1024=1.5625GB（没到60G，可能我算的不太对），你可以检查下是哪里占用比较大。另外，我见过一家公司，对占用较大的图像，自己制作了个图像浏览器，即图像还是一张张保存，然后记录位移信息，打开后给你看个缩略图，然后你想放大哪里，根据你的鼠标位置找到那张单独存放的小图给你展示，这样会有一点时延，但从另一个角度解决问题。
2. 你这个大小的图像用特征点拼接的话，建议使用GPU加速，我以前反编译cuda,opencv在windows下成功了，linux我没试，你可以尝试下；我个人感觉我在拼接，位移量这块的速度优化做的还行，你可以再试试能不能从其他角度提速，我建议你针对你的图像，输出每个阶段的时延，然后判断你要加速哪块；
3. 如果你图像中特征点数目过少，建议使用imageJ的基于相位相关的配准方法，但他没有用GPU加速，理论上在特征点数目小的情况下，使用相位相关速度快，效果好，但相位相关存在缺陷，即无法判断配准是否成功

**Comment by NextGuido** [comment]
1、我刚才又试了一下，可能之前描述有点夸大，这是我记录的内存占用情况[https://github.com/NextGuido/ImageStitch/blob/master/demoImages/aaa.jpg](url)，大概占用了40多G左右，期间没有进行过其他操作。关于图像浏览器我已经做好了，基于网页端的，现在只是拼图这一环节效果不太好。
2、pass
3、相位相关的配准方法有什么推荐的仓库吗？我之前对于传统的算法了解的很少，非常感谢

**Comment by MATony** [comment]
1. 我的代码分为两部分，图像配准和图像拼接（融合），图像配准主要通过特征搜索的方式搜索特征点，图像拼接（融合）主要耗内存是存储空间以及融合过程，我不太清楚你是哪块占用内存太大，如果是后者，你试试创建的时候改成uint8，我里面的-1操作是为了计算渐入渐出，三角函数融合方便，所以此时存的不是uint8，如果你不需要这两种融合，你可以修改我的代码，这样会减少内存消耗；
3. 相位相关法英文名phase correlate，opencv就有，但我测试过不太理想，github上我也测试过，都不算太好，最好的是imageJ，但是java写的，必须使用python调用java，当时太难，我就放弃了，你可以试试。。。

**Comment by NextGuido** [comment]
1、谢谢啦，我忘了，我之前将你的代码改为RGB三通道的了，所以占用内存会非常大，但是可以分别处理R、G、B三个通道，然后进行通道合并，这样内存占用会小一点
2、我看了imageJ的其中一个拼图的插件[MIST](https://github.com/USNISTGOV/MIST/tree/mist-matlab)，确实用的是相位相关和互相关，但是我发现他计算的偏移值效果并不是很好，反而是他的融合算法非常好用，推荐
3、我最近在看一个开源的图像处理库[libvips](https://github.com/libvips/libvips)，非常好用，低内存并且处理速度也很快，推荐。

最后，谢谢您的帮助

**Comment by MATony** [comment]
谢谢啦，我去试试libvips，另外我是用imageJ的这个插件：https://imagej.net/Image_Stitching；
